name: Build and test
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  test-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run --filter "./packages/syntax" format:check
      - run: bun run --filter "./packages/syntax" build
      - run: bun run --filter "./packages/syntax" test
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run --filter "./packages/core" format:check
      - run: bun run --filter "./packages/*" build
      - run: bun run --filter "./packages/core" test
  test-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run --filter "./packages/*" build
      - run: bun run --filter "./extensions/vscode" build
      - run: bun run --filter "./extensions/vscode" test